### ISSUE TITLE
Ability to pass user credentials from command line...

### ISSUE THREAD

**Issue by beggles** [xoanmi/ansible-infoblox#17]
With the release of Ansible 2.3 it was announced plans to deprecate use of username and password fields within play books, in favour of passing them in from the command line (and Tower). Is this something that you are looking at?

https://www.ansible.com/blog/network-device-authentication-with-ansible-2-3

**Comment by xoanmi** [comment]
You can pass it as extra variable if you want. I'm doing it and it works fine
