### ISSUE TITLE
delete_host does not remove a host

### ISSUE THREAD

**Issue by KrystianMarek** [xoanmi/ansible-infoblox#32]
If I try to remove a host with:
`---
- hosts: localhost
  connection: local
  tasks:
    - name: add_host
      infoblox:
        server: 172.37.2.1
        username: admin
        password: admin
        action: delete_host
        host: feature_x.project_k.awesome_domain.com
`
feature_x.project_k.awesome_domain.com is moved to 'Recycle Bin' - not fully removed.

**Comment by xoanmi** [comment]
No. This is the expected behaivor of the API and also from the webgui.
When you remove a object this is moved to Recycle Bin. You can recover the objects from there in case of disaster.
I think this is desirable instead of delete it permanently, most in automated environments.

**Comment by KrystianMarek** [comment]
Ok,
So how do I empty the Recycle Bin using the ansible module ?

**Comment by xoanmi** [comment]
Is not implemented. I'm not sure if the api supports it or not.
Anyway, feel free to open a pull request :)
