### ISSUE TITLE
GNU General Public License v3.0 Questions

### ISSUE THREAD

**Issue by antoineserrano** [xoanmi/ansible-infoblox#34]
Hi here,

I'd love to use this project in a corp environment, but for obvious reason can't open source the project I'll be working on.

Would you have any objection to change the License to a bit more permissive one like MIT/Apache 2.0 ?

Thanks for this super cool module :-).

**Comment by dseeley** [comment]
This would be very useful.

**Comment by xoanmi** [comment]
License changed to Apache License :)

**Comment by jdetroy** [comment]
Hello,

would this make inclusion of this module into the ansible core modules more
difficult or impossible?
Just asking.

Best Regards,
Jo

**Comment by dseeley** [comment]
My understanding is that the Apache license is more permissive, so it can be merged into a GPL3 project (but not vice-versa).
See also:  https://www.apache.org/licenses/GPL-compatibility.html

**Comment by xoanmi** [comment]
The only reason why this module is not on ansible core modules is beacause I don't have time to work on it.
On the other hand, Infoblox is working on theis own project so I hope they have it included on v2.5

**Comment by xoanmi** [comment]
https://github.com/ansible/ansible/pull/28055#issuecomment-337873748
