### ISSUE TITLE
Error when trying to use the module

### ISSUE THREAD

**Issue by techduderavi** [xoanmi/ansible-infoblox#42]
I am getting below error when trying to use the module.

****An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'module' object has no attribute 'urllib3'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_A88I7r/ansible_module_infoblox.py\", line 185, in <module>\n    requests.packages.urllib3.disable_warnings()\nAttributeError: 'module' object has no attribute 'urllib3'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}****

Ansible, python and WAPI versions below

**ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/my_modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May 29 2017, 20:42:36) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]**

WAPI version: 

**1.7.5**

**Comment by beggles** [comment]
@rtk88 The issue you are encountering is likely to do with the version of **requests** you have installed. We have seen the same problem running **2.18.4** on a new system, where one of our older systems is running **2.13.0** of requests and works as expected. 

Do a `pip install requests==2.13.0` to install the older version and see how you go.

@xoanmi, FYI

**Comment by xoanmi** [comment]
Thanks @beggles!

Any idea how to solve it and maintain and maintain backward compatibility?

Regards

**Comment by beggles** [comment]
@xoanmi As of 2.16.1 it seems the maintainer has altered the requests’ namespace, and suggests the following;

Note**: code that was written to import against the ``requests.packages``
namespace previously will have to import code that rests at this module-level
now.

For example::

from requests.packages.urllib3.poolmanager import PoolManager

Will need to be re-written to be::

from requests.packages import urllib3
urllib3.poolmanager.PoolManager

Or, even better::

from urllib3.poolmanager import PoolManager

**Comment by beggles** [comment]
Maybe changing this line of code;
requirements:
  - "requests >= 2.9.1"

To read as;
requirements:
  - "requests <= 2.16.0”

Or update the import to match up with the recommendations from the maintainer and update requirements to reflect the latest version.

**Comment by xoanmi** [comment]
Updated README and code documentation
