### ISSUE TITLE
Examples are incorrect

### ISSUE THREAD

**Issue by ghyde** [xoanmi/ansible-infoblox#6]
The examples in [example.yml](https://github.com/xoanmi/ansible-module-infoblox/blob/master/example.yml#L9) and the [README](https://github.com/xoanmi/ansible-module-infoblox/blob/master/README.md#playbooke-example) reference the parameter `ib_server`. It should be `server` according to [infoblox.py](https://github.com/xoanmi/ansible-module-infoblox/blob/master/infoblox.py#L312).

**Comment by xoanmi** [comment]
Hi ghyde!

Thanks so much for your contribution :)

Regards,
