### ISSUE TITLE
How to install...???

### ISSUE THREAD

**Issue by beggles** [xoanmi/ansible-infoblox#9]
Apologies if this is obvious, though I am new to Ansible and am keen to understand the process for installing your InfoBlox module. Appreciate if you could provide instructions for a newbie such as myself.

Thanks in advance.

**Comment by xoanmi** [comment]
Hi @beggles ,

You could copy the infoblox.py file into the ansible modules extras path (something like this: usr/lib/python2.7/site-packages/ansible/modules/extras).
You could also copy the python into a library folder in a role:

ansible/roles/your_role/
├── defaults
│   └── main.yml
├── handlers
│   └── main.yml
├── library
│   └── infoblox.py
├── meta
│   └── main.yml
├── README.md
├── tasks
│   ├── main.yml
├── tests
│   ├── inventory
│   └── test.yml
└── vars
    └── main.yml
